In [143]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn import linear_model

1. The following is the rundown of using Turn, Fade, and Net as independent variables.

In [38]:
disc = pd.read_csv("disc.csv")
disc.head()

Disc Manufacturer        Disc Type  Distance  Turn  Fade   Net
0  Delirium        Axiom  Distance Driver       461 -0.10  0.60  0.50
1   Raketen  Latitude 64  Distance Driver       459 -0.34  0.62  0.28
2  Corvette       Innova  Distance Driver       456 -0.19  0.39  0.20
3    Cannon       Legacy  Distance Driver       456 -0.44  0.49  0.05
4   Rampage       Legacy  Distance Driver       456 -0.17  0.77  0.60

In [135]:
reg = linear_model.LinearRegression()
reg.fit(disc[['Turn', 'Fade', 'Net']], disc.Distance)

LinearRegression()

In [128]:
reg.coef_

array([-22.575374  ,  21.84902059,  -0.72635341])

In [129]:
reg.intercept_

394.3378992952928

In [130]:
reg.predict([[-.1, .5, .6]])

array([407.08413494])

In [131]:
X = sm.add_constant(disc[['Turn', 'Fade', 'Net']])
model = sm.OLS(disc.Distance, X).fit()
print(model.rsquared_adj)

0.019952711912810117


In [132]:
run = []
dist = []
for i in range(0, 340):
    j = disc['Turn'].iloc[i]
    k = disc['Fade'].iloc[i]
    l = disc['Net'].iloc[i]
    m = disc['Distance'].iloc[i]
    n = reg.predict([[j, k, l]])
    run.append(float(n))
    dist.append(m)

In [133]:
run = np.array(run)
dist = np.array(dist)
run.reshape(1, -1)
dist.reshape(1, -1)

array([[461, 459, 456, 456, 456, 456, 455, 454, 454, 453, 453, 453, 452,
        451, 451, 451, 450, 450, 450, 450, 448, 448, 447, 445, 444, 444,
        444, 444, 443, 443, 443, 443, 442, 442, 442, 442, 441, 441, 440,
        440, 440, 439, 439, 439, 439, 439, 439, 439, 439, 439, 439, 438,
        438, 438, 438, 438, 438, 438, 438, 438, 437, 437, 437, 437, 437,
        436, 436, 436, 436, 436, 436, 436, 436, 435, 435, 435, 435, 435,
        435, 435, 435, 435, 435, 435, 435, 435, 435, 435, 435, 434, 434,
        434, 434, 434, 433, 433, 433, 433, 433, 432, 432, 432, 432, 432,
        432, 431, 431, 431, 431, 431, 431, 431, 431, 431, 431, 431, 430,
        428, 426, 425, 425, 425, 425, 424, 424, 423, 422, 422, 421, 421,
        421, 421, 421, 420, 420, 420, 420, 420, 420, 419, 419, 419, 419,
        419, 419, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418, 418,
        418, 418, 418, 417, 417, 417, 417, 417, 417, 417, 417, 417, 417,
        417, 416, 416, 416, 416, 416, 415, 415, 415

2. The following is the rundown of using Turn, Fade, Net, as well as an equally distributed arbitrary value used to tag the Manufacturer (denoted in column headed "-1").

In [56]:
disc1 = pd.read_csv("disc - Copy.csv")
disc1.head()

Disc              Manufacturer        Disc Type  \
0                   Bee Line                       ABC  Distance Driver   
1                  Gamma Ray                       ABC  Distance Driver   
2              Secret Weapon                       ABC  Distance Driver   
3                    Cypress  Above Ground Level Discs  Distance Driver   
4  D Model Distance Driver S           ACE Disc Sports  Distance Driver   

   Distance  Turn  Fade   Net      -1  
0       435 -0.52  0.39 -0.13 -0.9649  
1       401 -0.38  0.38  0.00 -0.9649  
2       379 -0.51  0.35 -0.16 -0.9649  
3       414  0.00  0.78  0.78 -0.9298  
4       440  0.00  0.39  0.39 -0.8947

In [57]:
reg1 = linear_model.LinearRegression()
reg1.fit(disc1[['Turn', 'Fade', 'Net', '-1']], disc1.Distance)

LinearRegression()

In [58]:
reg1.coef_

array([ 3.30326366e+15,  3.30326366e+15, -3.30326366e+15, -4.76562500e-01])

In [59]:
reg1.intercept_

395.9235294117647

In [61]:
reg1.predict([[-.1, .5, .6, -0.0874]])

array([-6.60652732e+14])

In [144]:
X1 = sm.add_constant(disc1[['Turn', 'Fade', 'Net', '-1']])
model1 = sm.OLS(disc1.Distance, X1).fit()
print(model1.rsquared_adj)

0.017117030926530052


3. The following is the rundown of just using Turn and Fade as independent variables.

In [138]:
reg2 = linear_model.LinearRegression()
reg2.fit(disc[['Turn', 'Fade']], disc.Distance)

LinearRegression()

In [139]:
reg2.coef_

array([-23.30172741,  21.12266718])

In [140]:
reg2.intercept_

394.3378992952928

In [141]:
reg2.predict([[-.1, .5]])

array([407.22940563])

In [142]:
X2 = sm.add_constant(disc[['Turn', 'Fade']])
model2 = sm.OLS(disc.Distance, X2).fit()
print(model2.rsquared_adj)

0.01995271191281034


4. The following is the rundown of just using Turn as an independent variable.

In [145]:
reg3 = linear_model.LinearRegression()
reg3.fit(disc[['Turn']], disc.Distance)

LinearRegression()

In [146]:
reg3.coef_

array([-13.16039308])

In [147]:
reg3.intercept_

407.4175408038969

In [148]:
reg3.predict([[-.1]])

array([408.73358011])

In [149]:
X3 = sm.add_constant(disc[['Turn']])
model3 = sm.OLS(disc.Distance, X3).fit()
print(model3.rsquared_adj)

0.008650304650240859


5. The following is the rundown of just using Fade as an independent variable.

In [150]:
reg4 = linear_model.LinearRegression()
reg4.fit(disc[['Fade']], disc.Distance)

LinearRegression()

In [151]:
reg4.coef_

array([5.26297352])

In [152]:
reg4.intercept_

407.74173481858304

In [157]:
reg4.predict([[.5]])

array([410.37322158])

In [154]:
X4 = sm.add_constant(disc[['Fade']])
model4 = sm.OLS(disc.Distance, X4).fit()
print(model4.rsquared_adj)

-0.001648931213076521
